# Use the official Python image from the Docker Hub
FROM alpine/dev/flask AS builder

RUN mkdir /usr/local/tmp && \
    cp -pr /usr/lib/libstdc++.so* /usr/local/tmp && \
    cp -pr /usr/lib/libgcc* /usr/local/tmp

FROM python:3.9-alpine

# Define correct paths for libstdc++ and libgcc
COPY --from=builder /usr/local/tmp/ /usr/lib/
COPY --from=builder /usr/local/lib/ /usr/local/lib/

# Install necessary system packages and dependencies
RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    geos-dev \
    gdal-dev \
    libpq

# Set the working directory
WORKDIR /app

# RUN wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz && \
#     tar zxvf ngrok-v3-stable-linux-amd64.tgz && rm ngrok-v3-stable-linux-amd64.tgz && \
#     mv /usr/local/ngrok /usr/local/bin

# Copy the requirements file and install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the Flask application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the Flask application
CMD ["flask", "run"]
